name: Build .NET

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/github-script@v6
      id: vars
      with:
        script: |
          const os = "${{ matrix.os }}";
          const platform = os.replace('ubuntu', 'linux');
          core.setOutput("platform", platform.replace('-latest', ''));
          const target = platform.replace('macos', 'osx').replace('windows', 'win');
          core.setOutput("target", target.replace('-latest', ''));
          const targetDir = target.replace('osx', 'mac');
          core.setOutput("targetDir", targetDir.replace('-latest', ''));
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: |
        dotnet restore
        dotnet tool install ElectronNET.CLI -g
    - name: Build
      run: electronize build /target ${{ steps.vars.outputs.target }}
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ChatroomFetcherElectron-${{ steps.vars.outputs.platform }}
        path: bin/Desktop/${{ steps.vars.outputs.targetDir }}-unpacked
